export const authorites = [
  // {
  //   key: 'inventory',
  //   label: '库存管理',
  //   value: 'inventory',
  // },
  // {
  //   key: 'inventory:warehouse',
  //   label: '仓库信息',
  //   parent: 'inventory',
  //   value: 'inventory:warehouse',
  // },
  // {
  //   key: 'inventory:warehouse:view',
  //   label: '查看仓库',
  //   parent: 'inventory:warehouse',
  //   value: 'inventory:warehouse:view',
  // },
  // {
  //   key: 'inventory:warehouse:edit',
  //   label: '编辑仓库',
  //   parent: 'inventory:warehouse',
  //   value: 'inventory:warehouse:edit',
  // },
  // {
  //   key: 'inventory:position',
  //   label: '仓位信息',
  //   parent: 'inventory',
  //   value: 'inventory:position',
  // },
  // {
  //   key: 'inventory:position:view',
  //   label: '查看仓位',
  //   parent: 'inventory:position',
  //   value: 'inventory:position:view',
  // },
  // {
  //   key: 'inventory:position:edit',
  //   label: '编辑仓位',
  //   parent: 'inventory:position',
  //   value: 'inventory:position:edit',
  // },
  // {
  //   key: 'inventory:shelf',
  //   label: '货架信息',
  //   parent: 'inventory',
  //   value: 'inventory:position',
  // },
  // {
  //   key: 'inventory:shelf:view',
  //   label: '查看货架',
  //   parent: 'inventory:shelf',
  //   value: 'inventory:shelf:view',
  // },
  // {
  //   key: 'inventory:shelf:edit',
  //   label: '编辑货架',
  //   parent: 'inventory:shelf',
  //   value: 'inventory:shelf:edit',
  // },
  {
    key: 'project',
    label: '项目管理',
    value: 'project',
  },
  {
    key: 'project:view',
    parent: 'project',
    label: '查看',
    value: 'project:view',
  },
  {
    key: 'project:edit',
    parent: 'project',
    label: '编辑',
    value: 'project:edit',
  },
  {
    key: 'project:projectAudit',
    parent: 'project',
    label: '立项审批',
    value: 'project:projectAudit',
  },
  {
    key: 'project:priceAudit',
    parent: 'project',
    label: '报价单审批',
    value: 'project:priceAudit',
  },
  {
    key: 'project:needAudit',
    parent: 'project',
    label: '特殊需求审批',
    value: 'project:needAudit',
  },
  {
    key: 'project:purchaseAudit',
    parent: 'project',
    label: '采购单审批',
    value: 'project:purchaseAudit',
  },
  {
    key: 'contacts',
    label: '往来单位管理',
    value: 'contacts',
  },
  {
    key: 'contacts:view',
    parent: 'contacts',
    label: '查看',
    value: 'contacts:view',
  },
  {
    key: 'contacts:edit',
    parent: 'contacts',
    label: '编辑',
    value: 'contacts:edit',
  },
  {
    key: 'inside',
    label: '内部管理',
    value: 'inside',
  },
  {
    key: 'inside:hire',
    parent: 'inside',
    label: '人事录用',
    value: 'inside:hire',
  },
  {
    key: 'inside:hire:view',
    parent: 'inside:hire',
    label: '查看',
    value: 'inside:hire:view',
  },
  {
    key: 'inside:hire:edit',
    parent: 'inside:hire',
    label: '编辑',
    value: 'inside:hire:edit',
  },
  {
    key: 'inside:hire:audit',
    parent: 'inside:hire',
    label: '审核',
    value: 'inside:hire:audit',
  },
  {
    key: 'inside:leave',
    parent: 'inside',
    label: '人事离职',
    value: 'inside:leave',
  },
  {
    key: 'inside:leave:view',
    parent: 'inside:leave',
    label: '查看',
    value: 'inside:leave:view',
  },
  {
    key: 'inside:leave:edit',
    parent: 'inside:leave',
    label: '编辑',
    value: 'inside:leave:edit',
  },
  {
    key: 'inside:leave:hrAudit',
    parent: 'inside:leave',
    label: '行政审批',
    value: 'inside:leave:hrAudit',
  },
  {
    key: 'inside:leave:inanceAudit',
    parent: 'inside:leave',
    label: '财务审批',
    value: 'inside:leave:inanceAudit',
  },
  {
    key: 'inside:leave:leaderAudit',
    parent: 'inside:leave',
    label: '经理审批',
    value: 'inside:leave:leaderAudit',
  },
  {
    key: 'inside:attendance',
    parent: 'inside',
    label: '考勤管理',
    value: 'inside:attendance',
  },
  {
    key: 'inside:attendance:view',
    parent: 'inside:attendance',
    label: '查看',
    value: 'inside:attendance:view',
  },
  {
    key: 'inside:attendance:edit',
    parent: 'inside:attendance',
    label: '编辑',
    value: 'inside:attendance:edit',
  },
  {
    key: 'inside:attendance:audit',
    parent: 'inside:attendance',
    label: '审核',
    value: 'inside:attendance:audit',
  },
  {
    key: 'inside:reimburse',
    parent: 'inside',
    label: '报销申请',
    value: 'inside:reimburse',
  },
  {
    key: 'inside:reimburse:view',
    parent: 'inside:reimburse',
    label: '查看',
    value: 'inside:reimburse:view',
  },
  {
    key: 'inside:reimburse:edit',
    parent: 'inside:reimburse',
    label: '编辑',
    value: 'inside:reimburse:edit',
  },
  {
    key: 'inside:reimburse:deptAudit',
    parent: 'inside:reimburse',
    label: '部门审批',
    value: 'inside:reimburse:audit',
  },
  {
    key: 'inside:reimburse:inanceAudit',
    parent: 'inside:reimburse',
    label: '财务审批',
    value: 'inside:reimburse:inanceAudit',
  },
  {
    key: 'inside:reimburse:leaderAudit',
    parent: 'inside:reimburse',
    label: '总经理审批',
    value: 'inside:reimburse:leaderAudit',
  },
  {
    key: 'staff',
    label: '员工管理',
    value: 'staff',
  },
  {
    key: 'staff:group',
    parent: 'staff',
    label: '部门信息',
    value: 'staff:group',
  },
  {
    key: 'staff:group:view',
    parent: 'staff:group',
    label: '查看部门',
    value: 'staff:group:view',
  },
  {
    key: 'staff:group:edit',
    parent: 'staff:group',
    label: '编辑部门',
    value: 'staff:group:edit',
  },
  {
    key: 'staff:role',
    parent: 'staff',
    label: '权限信息',
    value: 'staff:role',
  },
  {
    key: 'staff:role:view',
    parent: 'staff:role',
    label: '查看权限',
    value: 'staff:role:view',
  },
  {
    key: 'staff:role:edit',
    parent: 'staff:role',
    label: '编辑权限',
    value: 'staff:role:edit',
  },
  {
    key: 'staff:view',
    parent: 'staff',
    label: '查看',
    value: 'staff:view',
  },
  {
    key: 'staff:edit',
    parent: 'staff',
    label: '编辑',
    value: 'staff:edit',
  },
  {
    key: 'staff:user',
    parent: 'staff',
    label: '用户信息',
    value: 'staff:user',
  },
  {
    key: 'staff:user:view',
    parent: 'staff',
    label: '查看用户',
    value: 'staff:user:view',
  },
  {
    key: 'staff:user:edit',
    parent: 'staff',
    label: '编辑用户',
    value: 'staff:user:edit',
  },
];
