
export const OreList = {
  Mn: {
    label: '锰矿',
    attrs: [{
      label: 'H2O（水分）',
      field: 'H2O',
      suffix: '%',
    }, {
      label: 'MN（锰）',
      field: 'MN',
      suffix: '%',
    }, {
      label: 'FE（铁）',
      field: 'FE',
      suffix: '%',
    }, {
      label: 'SIO2（二氧化硅）',
      field: 'SIO2',
      suffix: '%',
    }, {
      label: 'AL2O3（二氧化二铝）',
      field: 'AL2O3',
      suffix: '%',
    }, {
      label: 'P（磷）',
      field: 'P',
      suffix: '%',
    }, {
      label: 'MGO（氧化镁）',
      field: 'MGO',
      suffix: '%',
    }, {
      label: '6.3-100MM（粒度）',
      field: '6dot3-100MM',
      suffix: '%',
    }, {
      label: 'S（硫）',
      field: 'S',
      suffix: '%',
    }],
  },
  Cr: {
    label: '铬矿',
    attrs: [{
      label: 'H2O（水分）',
      field: 'H2O',
      suffix: '%',
    }, {
      label: 'Cr2O3（三氧化二铬）',
      field: 'Cr203',
      suffix: '%',
    }, {
      label: 'SiO2（二氧化硅）',
      field: 'SiO2',
      suffix: '%',
    }, {
      label: 'MGO（氧化镁）',
      field: 'MGO',
      suffix: '%',
    }, {
      label: 'AL2O3（三氧化二铝）',
      field: 'AL2O3',
      suffix: '%',
    }, {
      label: 'P（磷）',
      field: 'P',
      suffix: '%',
    }, {
      label: 'S（硫）',
      field: 'S',
      suffix: '%',
    }, {
      label: 'Cr：Fe（铬：铁）',
      field: 'Cr:Fe',
      placeholder: '例如：1:25',
    }, {
      label: 'MgO：AL2O3（氧化镁：三氧化二铝）',
      field: 'MgO:AL2O3',
      placeholder: '例如：1:25',
    }, {
      label: '粒度（块）10-300mm',
      field: 'block10-300MM',
      suffix: '%',
    }, {
      label: '粒度（粉）0-10mm',
      field: 'powder10-300MM',
      suffix: '%',
    }],
  },
};
